import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "../lib/redux/StoreProvider";
import "./globals.css";
import { Presenter } from "@/components";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Store 2023</title>
        <meta name="Store" content="Store" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <body>
        <Provider>
          <Presenter>{children}</Presenter>
        </Provider>
      </body>
    </html>
  );
}
